micronaut:
  application:
    name: mnStockBrokerLegacy
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mappping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mappping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
